/* Kairu MCQ Engine — vanilla JS, no deps */
(function(){
  'use strict';

  // Robust KaTeX renderer. Handles three failure modes:
  //   (1) KaTeX not loaded yet — re-tries every 80ms until it is
  //   (2) KaTeX throws on a single bad expression — silently moves on
  //   (3) Multiple rapid renders — uses a debounce flag
  let _kx_pending = false;
  function renderMath(){
    if(typeof renderMathInElement !== 'function'){
      // not loaded yet — schedule retry
      if(_kx_pending) return;
      _kx_pending = true;
      const tick = () => {
        _kx_pending = false;
        if(typeof renderMathInElement === 'function'){ renderMath(); }
        else { setTimeout(() => { _kx_pending = true; tick(); }, 80); }
      };
      setTimeout(tick, 80);
      return;
    }
    try {
      renderMathInElement(root, {
        delimiters: [
          {left: '\\[', right: '\\]', display: true},
          {left: '\\(', right: '\\)', display: false},
        ],
        throwOnError: false,
        errorColor: '#dc2626',
        ignoredTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code', 'kbd'],
      });
    } catch(e){ console.warn('[katex render]', e); }
  }
  // Re-render once KaTeX finishes loading (catches first-paint race)
  if(typeof window !== 'undefined'){
    window.addEventListener('load', function(){
      if(typeof renderMathInElement === 'function') renderMath();
    });
  }

  const params = new URLSearchParams(location.search);
  const subject = params.get('subject');
  const root = document.getElementById('mcq-root');
  const titleEl = document.getElementById('mcq-title');
  const stopBtn = document.getElementById('mcq-stop');

  if(!subject){
    root.innerHTML = '<div class="muted" style="text-align:center;padding:60px">No subject selected. <a href="index.html">Back to subjects</a></div>';
    return;
  }

  let data = null;
  let session = null;

  function kairuStamp(opts){
    opts = opts || {};
    const reviewed = opts.reviewed === true;
    const bird = '<span class="kairu-bird"><svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><path d="M32 22 Q22 8 8 14 Q14 24 24 28" fill="#fde68a"/><ellipse cx="36" cy="34" rx="14" ry="9" fill="#f5a623"/><circle cx="24" cy="28" r="7" fill="#fbbf24"/><circle cx="22" cy="26" r="1.5" fill="#1a2332"/><path d="M16 27 L6 25 L16 30 Z" fill="#1a2332"/><path d="M48 32 L60 28 L60 38 L50 36 Z" fill="#f5a623"/></svg></span>';
    if(reviewed){
      return '<div class="kairu-stamp reviewed">'+bird+'<div><em>Solution reviewed by Kerwin Springer.</em> Originally generated by Kairu — Student Hub\'s AI system, trained by The Student Hub.</div></div>';
    }
    return '<div class="kairu-stamp">'+bird+'<div><em>Solution generated by Kairu</em> — Student Hub\'s AI system, trained by The Student Hub.</div></div>';
  }

  function maybeShowGreeting(){
    const key = 'kairu-mcq-greeted-'+subject;
    if(localStorage.getItem(key) === 'yes') return Promise.resolve();
    return new Promise(function(resolve){
      const veil = document.createElement('div');
      veil.className = 'modal-veil';
      veil.innerHTML = '<div class="modal-card"><div class="modal-bird"><svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><path d="M32 22 Q22 8 8 14 Q14 24 24 28" fill="#fde68a"/><ellipse cx="36" cy="34" rx="14" ry="9" fill="#f5a623"/><circle cx="24" cy="28" r="7" fill="#fbbf24"/><circle cx="22" cy="26" r="1.5" fill="#1a2332"/><path d="M16 27 L6 25 L16 30 Z" fill="#1a2332"/><path d="M48 32 L60 28 L60 38 L50 36 Z" fill="#f5a623"/></svg></div><h2>Hey from Kairu</h2><p id="modal-msg"></p><button id="modal-ok">Got it — let\'s go</button></div>';
      document.body.appendChild(veil);
      document.getElementById('modal-msg').textContent = data.greeting || 'Welcome! Ready to revise?';
      document.getElementById('modal-ok').addEventListener('click', function(){
        localStorage.setItem(key, 'yes');
        veil.remove();
        resolve();
      });
    });
  }

  function renderModePicker(){
    titleEl.textContent = data.subjectName + ' — P1 Multiple Choice Revision';
    document.title = titleEl.textContent;

    const topics = data.topics || [];
    const topicChips = topics.map(function(t){
      return '<button type="button" class="mode-btn topic-chip" data-topic="'+t+'">'+t+'</button>';
    }).join('');

    root.innerHTML =
      '<div class="mode-card"><h2>Choose mode</h2>' +
        '<div class="mode-options" id="modes">' +
          '<button class="mode-btn selected" data-mode="endless">Endless<small>Stop anytime</small></button>' +
          '<button class="mode-btn" data-mode="10">10 Questions<small>Quick warm-up</small></button>' +
          '<button class="mode-btn" data-mode="25">25 Questions<small>Solid drill</small></button>' +
          '<button class="mode-btn" data-mode="50">50 Questions<small>Half paper</small></button>' +
          '<button class="mode-btn" data-mode="60">Mock P1<small>60 questions, exam length</small></button>' +
        '</div>' +
        (topics.length > 1 ? '<h2 style="margin-top:14px">Topics <span style="font-weight:400;font-size:12px;color:var(--text-tertiary)">(optional — leave all selected for mixed)</span></h2><div class="mode-options" id="topics">'+topicChips+'</div>' : '') +
        '<button class="start-btn" id="start">Start Practice →</button>' +
        '<div class="hint-row" style="text-align:center;margin-top:14px;font-size:12px;color:var(--text-tertiary)">Tip: once playing, use <kbd>←</kbd> <kbd>→</kbd> arrow keys to skip, go back, or move forward.</div>' +
      '</div>' +
      kairuStamp();

    let mode = 'endless';
    document.getElementById('modes').addEventListener('click', function(e){
      const btn = e.target.closest('[data-mode]');
      if(!btn) return;
      document.querySelectorAll('#modes .mode-btn').forEach(function(b){b.classList.remove('selected')});
      btn.classList.add('selected');
      mode = btn.getAttribute('data-mode');
    });

    let excludedTopics = new Set();
    const topicsEl = document.getElementById('topics');
    if(topicsEl){
      topicsEl.querySelectorAll('.topic-chip').forEach(function(b){b.classList.add('selected')});
      topicsEl.addEventListener('click', function(e){
        const btn = e.target.closest('.topic-chip');
        if(!btn) return;
        const t = btn.getAttribute('data-topic');
        btn.classList.toggle('selected');
        if(btn.classList.contains('selected')) excludedTopics.delete(t);
        else excludedTopics.add(t);
      });
    }

    document.getElementById('start').addEventListener('click', function(){
      const filtered = data.questions.filter(function(q){return !excludedTopics.has(q.topic)});
      if(filtered.length === 0){
        alert('No questions match your filters — try selecting more topics.');
        return;
      }
      startSession({mode: mode, pool: shuffle(filtered.slice())});
    });
  }

  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

  function startSession(opts){
    session = {
      mode: opts.mode,
      pool: opts.pool,            // ordered list of questions
      idx: 0,                     // current position
      target: opts.mode === 'endless' ? Infinity : parseInt(opts.mode, 10),
      // Per-question state, keyed by question id
      // entry: { picked: 'A'|'B'|'C'|'D'|null, status: 'unanswered'|'correct'|'wrong'|'skipped' }
      state: {},
      // Final tally is computed at finish (counts based on state)
    };
    opts.pool.forEach(function(q){
      session.state[q.id] = {picked:null, status:'unanswered'};
    });
    stopBtn.hidden = false;
    renderQuestion();
  }

  function tally(){
    let right=0, wrong=0, skipped=0, unanswered=0;
    for (const id in session.state){
      const st = session.state[id];
      if(st.status === 'correct') right++;
      else if(st.status === 'wrong') wrong++;
      else if(st.status === 'skipped') skipped++;
      else unanswered++;
    }
    return {right:right, wrong:wrong, skipped:skipped, unanswered:unanswered};
  }

  function renderQuestion(){
    const cap = isFinite(session.target) ? session.target : session.pool.length;
    if(session.idx >= session.pool.length || session.idx >= session.target){
      finish();
      return;
    }
    const q = session.pool[session.idx];
    const st = session.state[q.id];
    const t = tally();
    const total = isFinite(session.target) ? session.target : session.pool.length;
    const pct = isFinite(session.target) ? Math.min(100, Math.round((session.idx / session.target) * 100)) : Math.round(100*session.idx/Math.max(1,session.pool.length));

    let diagramHtml = '';
    if(q.diagram){
      if(q.diagram.type === 'svg') diagramHtml = '<div class="q-diagram" role="img" aria-label="'+(q.diagram.alt||'')+'">'+q.diagram.content+'</div>';
      else if(q.diagram.type === 'image') diagramHtml = '<div class="q-diagram"><img src="'+q.diagram.src+'" alt="'+(q.diagram.alt||'')+'"></div>';
    }

    const optsHtml = ['A','B','C','D'].map(function(letter){
      const text = (q.options && q.options[letter]) || '';
      const optDiag = q.optionDiagrams && q.optionDiagrams[letter];
      const imgHtml = optDiag ? '<img class="opt-img" src="'+optDiag+'" alt="Option '+letter+'">' : '';
      let cls = 'opt-btn';
      // if already answered, mark up persistent state
      if(st.status !== 'unanswered'){
        if(letter === q.answer) cls += ' correct';
        else if(letter === st.picked) cls += ' wrong';
        else cls += ' dimmed';
      }
      return '<button class="'+cls+'" data-letter="'+letter+'"><span class="opt-letter">'+letter+'</span><span class="opt-text">'+text+imgHtml+'</span></button>';
    }).join('');

    const scoreStrip =
      '<div class="score-strip">' +
        '<span>Q '+(session.idx+1)+(isFinite(session.target) ? ' / '+session.target : ' / '+session.pool.length)+'</span>' +
        '<span class="score-pill right">✓ '+t.right+'</span>' +
        '<span class="score-pill wrong">✗ '+t.wrong+'</span>' +
        (t.skipped > 0 ? '<span class="score-pill skipped">↷ '+t.skipped+'</span>' : '') +
        '<div class="score-progress"><div class="score-progress-fill" style="width:'+pct+'%"></div></div>' +
      '</div>';

    const isAnswered = st.status === 'correct' || st.status === 'wrong';

    // Explanation only shown if answered
    let explHtml = '';
    if(isAnswered){
      const distractorBlocks = [];
      if(st.status === 'wrong' && q.distractors && q.distractors[st.picked]){
        distractorBlocks.push('<div class="expl-distractor"><strong>Why '+st.picked+' is wrong:</strong> '+q.distractors[st.picked]+'</div>');
      }
      explHtml =
        '<div class="expl">' +
          '<div class="expl-head '+(st.status==='correct'?'expl-correct':'expl-incorrect')+'">'+(st.status==='correct'?'✓ Correct':'✗ Not quite — answer is '+q.answer)+'</div>' +
          '<div class="expl-body">'+(q.explanation||'')+'</div>' +
          distractorBlocks.join('') +
          kairuStamp({reviewed:false}) +
        '</div>';
    } else if(st.status === 'skipped'){
      explHtml = '<div class="expl skipped-note"><div class="expl-head">↷ Skipped — come back to this one if you like</div></div>';
    }

    // Navigation row
    const canPrev = session.idx > 0;
    const canNext = session.idx < session.pool.length - 1 && session.idx < session.target - 1;
    const navHtml =
      '<div class="q-nav">' +
        '<button class="nav-btn nav-prev" id="nav-prev"' + (canPrev ? '' : ' disabled') + ' title="Previous question (←)">‹ Previous</button>' +
        (isAnswered ? '' : '<button class="nav-btn nav-skip" id="nav-skip" title="Skip without answering">Skip</button>') +
        '<button class="nav-btn nav-next" id="nav-next"' + (canNext ? '' : ' disabled') + ' title="Next question (→)">' + (isAnswered ? 'Next →' : 'Next →') + '</button>' +
      '</div>';

    root.innerHTML = scoreStrip +
      '<div class="q-card">' +
        '<div class="q-meta">' +
          '<span class="q-meta-pill">'+(q.topic||'')+'</span>' +
          (q.subtopic ? '<span class="q-meta-pill">'+q.subtopic+'</span>' : '') +
          '<span class="q-meta-pill diff-'+(q.difficulty||'standard')+'">'+(q.difficulty||'standard')+'</span>' +
          '<span class="q-meta-status status-'+st.status+'">'+statusLabel(st.status)+'</span>' +
        '</div>' +
        '<div class="q-stem">'+(q.stem||'')+'</div>' +
        diagramHtml +
        '<div class="q-options">'+optsHtml+'</div>' +
        explHtml +
        navHtml +
      '</div>';

    renderMath();

    // Hook up answer buttons (only if unanswered)
    if(!isAnswered && st.status !== 'skipped'){
      document.querySelectorAll('.opt-btn').forEach(function(btn){
        btn.addEventListener('click', function(){answer(btn.getAttribute('data-letter'), q)});
      });
    } else {
      // Allow re-clicking won't change anything
      document.querySelectorAll('.opt-btn').forEach(function(btn){btn.disabled = true});
    }

    // Nav handlers
    const prevBtn = document.getElementById('nav-prev');
    const nextBtn = document.getElementById('nav-next');
    const skipBtn = document.getElementById('nav-skip');
    if(prevBtn) prevBtn.addEventListener('click', goPrev);
    if(nextBtn) nextBtn.addEventListener('click', goNext);
    if(skipBtn) skipBtn.addEventListener('click', function(){
      // Mark skipped (only if unanswered) and advance
      if(session.state[q.id].status === 'unanswered'){
        session.state[q.id].status = 'skipped';
      }
      goNext();
    });

    // Auto-focus next button after answering for keyboard flow
    if(isAnswered && nextBtn && !nextBtn.disabled) nextBtn.focus();
  }

  function statusLabel(s){
    if(s === 'correct') return 'answered ✓';
    if(s === 'wrong') return 'answered ✗';
    if(s === 'skipped') return 'skipped';
    return '';
  }

  function answer(letter, q){
    const st = session.state[q.id];
    if(st.status === 'correct' || st.status === 'wrong') return; // already answered
    st.picked = letter;
    st.status = (letter === q.answer) ? 'correct' : 'wrong';
    renderQuestion();
  }

  function goPrev(){
    if(session.idx > 0){
      session.idx--;
      renderQuestion();
    }
  }
  function goNext(){
    const cap = isFinite(session.target) ? session.target : session.pool.length;
    if(session.idx < session.pool.length - 1 && session.idx < cap - 1){
      session.idx++;
      renderQuestion();
    } else {
      // At end → finish
      finish();
    }
  }

  function finish(){
    stopBtn.hidden = true;
    const t = tally();
    const answered = t.right + t.wrong;
    const pct = answered ? Math.round((t.right / answered) * 100) : 0;

    // Compute weak topics from wrong answers
    const topicWrong = {};
    const wrongIds = [];
    for(let i=0;i<session.pool.length && i < (isFinite(session.target)?session.target:session.pool.length);i++){
      const q = session.pool[i];
      const st = session.state[q.id];
      if(st.status === 'wrong'){
        wrongIds.push(q.id);
        topicWrong[q.topic] = (topicWrong[q.topic]||0)+1;
      }
    }
    const weakTopics = Object.keys(topicWrong).sort(function(a,b){return topicWrong[b]-topicWrong[a]}).slice(0,5);
    const weakHtml = weakTopics.length ?
      '<div class="weak-spots"><h3>Topics to revisit</h3><ul>'+weakTopics.map(function(t){return '<li>• '+t+' — '+topicWrong[t]+' wrong</li>'}).join('')+'</ul></div>'
      : '';

    const verdict = pct >= 80 ? 'Excellent work' : pct >= 60 ? 'Solid effort' : pct >= 40 ? 'Building it up' : (answered === 0 ? 'No answers locked in' : 'Just getting warmed up');

    root.innerHTML =
      '<div class="scorecard">' +
        '<h2>'+verdict+'</h2>' +
        '<div class="big-score">'+t.right+' / '+answered+'</div>' +
        '<div class="big-pct">'+pct+'% correct</div>' +
        '<div class="breakdown">' +
          '<span><strong>'+t.right+'</strong> right</span>' +
          '<span><strong>'+t.wrong+'</strong> wrong</span>' +
          (t.skipped > 0 ? '<span><strong>'+t.skipped+'</strong> skipped</span>' : '') +
        '</div>' +
        '<div class="actions">' +
          (wrongIds.length ? '<button id="retry-wrong">Re-drill weak spots ('+wrongIds.length+')</button>' : '') +
          '<button id="restart">Start over</button>' +
          '<a href="index.html" class="secondary">Pick another subject</a>' +
        '</div>' +
        weakHtml +
      '</div>';

    if(wrongIds.length){
      document.getElementById('retry-wrong').addEventListener('click', function(){
        const wrongPool = data.questions.filter(function(q){return wrongIds.indexOf(q.id) !== -1});
        startSession({mode:'endless', pool: shuffle(wrongPool.slice())});
      });
    }
    document.getElementById('restart').addEventListener('click', function(){
      renderModePicker();
    });
  }

  function escapeHtml(s){
    if(s == null) return '';
    return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  // Stop button → finish session immediately
  stopBtn.addEventListener('click', function(){
    if(!session) return;
    if(confirm('Stop the quiz now and see your score?')){
      finish();
    }
  });

  // Global keyboard nav: ← prev, → next, S skip
  document.addEventListener('keydown', function(e){
    if(!session) return;
    // Only when not typing in an input
    const tag = (e.target && e.target.tagName) || '';
    if(tag === 'INPUT' || tag === 'TEXTAREA') return;
    if(e.key === 'ArrowLeft'){ e.preventDefault(); goPrev(); }
    else if(e.key === 'ArrowRight'){ e.preventDefault(); goNext(); }
    else if(e.key === 's' || e.key === 'S'){
      // Skip current if unanswered
      const q = session.pool[session.idx];
      const st = session.state[q.id];
      if(st.status === 'unanswered'){
        st.status = 'skipped';
        goNext();
      }
    }
  });

  // Boot
  // Cache-bust JSON fetches — read site-version from <meta name="site-version"> in quiz.html, fallback to load time
  const _sv = (document.querySelector('meta[name="site-version"]') || {}).content || String(Date.now());
  fetch('data/'+subject+'.json?v='+encodeURIComponent(_sv))
    .then(function(r){
      if(!r.ok) throw new Error('No data for '+subject);
      return r.json();
    })
    .then(function(json){
      data = json;
      maybeShowGreeting().then(renderModePicker);
    })
    .catch(function(err){
      root.innerHTML = '<div class="muted" style="text-align:center;padding:60px">Could not load <strong>'+subject+'</strong> question bank. <br><small>'+err.message+'</small><br><br><a href="index.html">Back to subjects</a></div>';
    });
})();
